### ISSUE TITLE
The README compares to TruffleRuby Native and not TruffleRuby JVM

### ISSUE THREAD

**Issue by eregon** [sisshiki1969/monoruby#48]
But as documented [here](https://github.com/oracle/truffleruby/blob/master/doc/user/benchmarking.md) for best peak performance TruffleRuby JVM should be used.

**Comment by sisshiki1969** [comment]
Sorry, I did not know the difference between truffleruby+graalvm (JVM) and truffleruby (NATIVE) well.
I had tested both, and truffleruby(NATIVE) performed better in my environment, so I took that one.
I have updated the README with the benchmark results using the latest release (24.0.1) of both.

**Comment by eregon** [comment]
Thank you for measuring both.

Right, I guess the slower JVM mode is expected (except on OptCarrot, good) because the micro benchmarks have no warmup, because benchmark-driver is known to not have warmup: https://github.com/benchmark-driver/benchmark-driver/issues/68 and benchmarks like https://github.com/sisshiki1969/monoruby/blob/master/benchmark/so_mandelbrot.rb run a single iteration per process.

Could you run micro benchmarks with proper warmup?
From the literature, warmup is expected for micro benchmarks when using JIT compilers.

For instance by using `benchmark-ips` (can be used without being installed as a gem) or simply adding something like `30.times { p Benchmark.realtime { ... } }` around the benchmark.
I suspect the results would change significantly.

Until then, it seems important to clarify in the results in the README that there is no warmup.

**Comment by eregon** [comment]
I want to also leave a positive note and say monoruby's results so far look impressive. However it's also hard to assess without a proper benchmarking setup (which means having enough warmup).

**Comment by sisshiki1969** [comment]
One of the monoruby's technical sales points is, it needs almost no warming up.

By the way, `benchmark-driver` has an optional setting of warming-up cycles before measurements for JIT compilers.
The benchmarks on `Truffleruby` got significantly faster when sufficient warm up cycles were given.
README was updated using the data, so please check it.

(I really wanted to use `yjit-bench`, but it does not work yet because `yjit-bench`'s harness uses several libraries which include C extensions, and these must work on the target implementation.)

**Comment by sisshiki1969** [comment]
Oh, I noticed this discussion https://github.com/benchmark-driver/benchmark-driver/issues/68 now.
I think it was warm-up'ed well in the case of so_nbody.yml (because frequently called methods are defined in the prelude),

**Comment by eregon** [comment]
> I think it was warm-up'ed well in the case of so_nbody.yml (because frequently called methods are defined in the prelude),

I don't see any call in the prelude:
https://github.com/sisshiki1969/monoruby/blob/8ebdfddf5928e07bb9bca8c3489d3107542989e0/benchmark/so_nbody.yml#L2-L118
except Planet.new but that only does a little arithmetic and is never used later.
IOW all relevant compilations for that nbody benchmark seem counted against the reported time.

**Comment by sisshiki1969** [comment]
That makes sense.

(I mistakenly thought that it would be better to define frequently-called-functions in prelude so that the JIT compilation which occurs during warm-up would not be "wasted".)

It seems to me that simply increasing the `loop_count` would give a "more" correct result. (I know not really "exact", but we can get a kind of "diluted" stuff)

I got the results below with `loop_count` = 1000. Does this make sence?

|      |truffleruby+graalvm-24.0.1| truffleruby-24.0.1|monoruby|
|:-----------|-------------------------:|------------------:|-----------------------------------:|
|fib         |                    28.063|             88.199|                              36.315|
|mandelbrot  |                    40.176|             41.082|                              31.277|
|nbody       |                    93.779|             95.336|                              15.778|

**Comment by eregon** [comment]
Yeah, those results look good.
`fib` on JVM seems quite a bit slower than on Native, a bit strange but it's expected to be a bit slower because Native is able to avoid boxing, which might explain this difference.

Have you tried using `.yml` and no `loop_count`?
I *think* benchmark-driver would then automatically run for `--run-duration` seconds (default 3), so bumping that to 10 or 30 might give stable results without needing to hardcode any loop_count.

As written on https://github.com/oracle/truffleruby/blob/master/doc/user/benchmarking.md#run-with-enough-warmup the easiest way to ensure there is enough warmup is to compare with numbers with more warmup, if it's still the same results and there is a low error/deviation inside a run then there is typically enough warmup.

**Comment by sisshiki1969** [comment]
Finally, monoruby works with yjit-bench. (Fiddle and JSON are now partially supported in monoruby)
It seems that TruffleNative outperforms TruffleJVM in performance for almost all benchmarks.

- yjit-bench results ( ratio to 3.3.1 of  iter/sec ) are shown.
- the higher, the better.

|bench|3.3.1|monoruby(noJIT)|3.3.1+YJIT|monoruby|TruffleNative|TruffleJVM|
|:-------|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|
|aobench|1.00|0.88|1.79|5.89|37.14|30.13|
|binarytrees|1.00|0.69|2.06|1.16|5.19|4.77|
|matmul|1.00|0.76|2.27|6.28|148.34|146.19|
|nbody|1.00|0.79|2.15|6.06|42.90|41.46|
|nqueens|1.00|1.28|1.03|7.40|15.47|15.30|
|optcarrot|1.00|0.83|4.07|4.87|6.08|6.48|
|mandelbrot|1.00|1.13|2.04|28.67|35.42|35.85|
|sudoku|1.00|1.16|4.26|6.77|14.23|11.79|
|fib|1.00|1.81|6.03|6.03|11.73|5.78|

- raw date is here.
- millisec/iter.

|bench|3.3.1|monoruby(noJIT)|3.3.1+YJIT|monoruby|TruffleNative|TruffleJVM|
|:-------|:-------:|:-------:|:-------:|:-------:|:-------:|:-------:|
|aobench|20816.76|23683.57|11617.77|3534.42|560.44|690.85|
|binarytrees|185.54|267.07|90.11|159.98|35.77|38.93|
|matmul|872.01|1143.60|383.88|138.90|5.88|5.96|
|nbody|64.27|80.93|29.92|10.60|1.50|1.55|
|nqueens|130.73|102.04|127.03|17.68|8.45|8.54|
|optcarrot|2902.14|3503.14|712.89|595.58|477.43|448.07|
|mandelbrot|1087.50|961.15|532.10|37.93|30.70|30.33|
|sudoku|1155.41|999.08|271.44|170.60|81.22|98.02|
|fib|123.26|68.21|20.44|20.45|10.51|21.31|

**Comment by eregon** [comment]
Nice.
TruffleNative/TruffleJVM look close for most benchmarks, so that seems reasonable. For aobench & sudoku I'd expect JVM is faster with enough warmup.
Which harness did you use for yjit-bench?
The default harness might not have enough warmup (it's just a fixed amount, good enough some benchmarks but not enough for others benchmarks), there is https://github.com/Shopify/yjit-bench/tree/main/harness-warmup which automatically runs with enough warmup.

**Comment by sisshiki1969** [comment]
I did it with default harness.
I tried, but monoruby crashed with harness-warmup.
It seems to be a parser's bug...

**Comment by sisshiki1969** [comment]
Fixed, and worked,
It seems almost same results compared with default harness?

run_benchmarks.rb --harness=harness-warmup

| bench         | monoruby (ms) | TruffleNative (ms) | TruffleJVM (ms) |
| :------------ | ------------: | -----------------: | --------------: |
| aobench       |   3189.746082 |        527.0056537 |     437.9900052 |
| binarytrees   |   150.3562119 |        36.03864932 |     40.10069695 |
| matmul        |   134.7295191 |        6.194924957 |     5.887552551 |
| nbody         |   10.00697308 |        1.484955227 |     1.416544854 |
| nqueens       |   17.27143996 |        8.151990576 |     7.969694405 |
| optcarrot     |    609.926476 |        477.6820806 |     379.7308686 |
| so_mandelbrot |   36.13658404 |        29.32767799 |     29.29997983 |
| sudoku        |   163.9368835 |        72.29677739 |      93.6846979 |
| fib           |   19.47258321 |        10.81266822 |     19.25076944 |
